#loc = loc("/mnt/e/Laboratory/Repo2Book/instances/triton/artifacts/ch09-self-hosted-libraries/explainer/traces/run_ir_metrics.py":21:0)
module {
  tt.func public @khint(%arg0: !tt.ptr<f32> loc("/mnt/e/Laboratory/Repo2Book/instances/triton/artifacts/ch09-self-hosted-libraries/explainer/traces/run_ir_metrics.py":21:0), %arg1: !tt.ptr<f32> loc("/mnt/e/Laboratory/Repo2Book/instances/triton/artifacts/ch09-self-hosted-libraries/explainer/traces/run_ir_metrics.py":21:0)) attributes {noinline = false} {
    %cst = arith.constant dense<1.000000e+00> : tensor<128xf32> loc(#loc1)
    %0 = tt.make_range {end = 128 : i32, start = 0 : i32, tt.divisibility = dense<128> : tensor<1xi32>} : tensor<128xi32> loc(#loc2)
    %1 = tt.splat %arg1 : !tt.ptr<f32> -> tensor<128x!tt.ptr<f32>> loc(#loc3)
    %2 = tt.addptr %1, %0 : tensor<128x!tt.ptr<f32>>, tensor<128xi32> loc(#loc3)
    %3 = tt.splat %arg0 : !tt.ptr<f32> -> tensor<128x!tt.ptr<f32>> loc(#loc4)
    %4 = tt.addptr %3, %0 : tensor<128x!tt.ptr<f32>>, tensor<128xi32> loc(#loc4)
    %5 = tt.load %4 : tensor<128x!tt.ptr<f32>> loc(#loc5)
    %6 = arith.addf %5, %cst : tensor<128xf32> loc(#loc6)
    tt.store %2, %6 : tensor<128x!tt.ptr<f32>> loc(#loc7)
    tt.return loc(#loc8)
  } loc(#loc)
} loc(#loc)
#loc1 = loc(unknown)
#loc2 = loc("/mnt/e/Laboratory/Repo2Book/instances/triton/artifacts/ch09-self-hosted-libraries/explainer/traces/run_ir_metrics.py":22:23)
#loc3 = loc("/mnt/e/Laboratory/Repo2Book/instances/triton/artifacts/ch09-self-hosted-libraries/explainer/traces/run_ir_metrics.py":23:17)
#loc4 = loc("/mnt/e/Laboratory/Repo2Book/instances/triton/artifacts/ch09-self-hosted-libraries/explainer/traces/run_ir_metrics.py":23:34)
#loc5 = loc("/mnt/e/Laboratory/Repo2Book/instances/triton/artifacts/ch09-self-hosted-libraries/explainer/traces/run_ir_metrics.py":23:30)
#loc6 = loc("/mnt/e/Laboratory/Repo2Book/instances/triton/artifacts/ch09-self-hosted-libraries/explainer/traces/run_ir_metrics.py":23:41)
#loc7 = loc("/mnt/e/Laboratory/Repo2Book/instances/triton/artifacts/ch09-self-hosted-libraries/explainer/traces/run_ir_metrics.py":23:22)
#loc8 = loc("/mnt/e/Laboratory/Repo2Book/instances/triton/artifacts/ch09-self-hosted-libraries/explainer/traces/run_ir_metrics.py":23:4)
